spring:
  profiles:
    active: local
    
security:
  oauth2:
    client:
      clientId: 467796897119-65otkjar9llmcco8otkvgjlgqakpj2of.apps.googleusercontent.com
      clientSecret: _vQDxlRplUgrIvVDnz4F1sfy
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true

server:
  port: 8082