-- MySQL Script generated by MySQL Workbench
-- jue 10 mar 2016 10:38:22 ART
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema exampleapi
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `exampleapi` ;

-- -----------------------------------------------------
-- Schema exampleapi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exampleapi` DEFAULT CHARACTER SET utf8 ;
USE `exampleapi` ;

-- -----------------------------------------------------
-- Table `exampleapi`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exampleapi`.`city` ;

CREATE TABLE IF NOT EXISTS `exampleapi`.`city` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO exampleapi.city (name, country) VALUES ('Resistencia', 'Argentina');
INSERT INTO exampleapi.city (name, country) VALUES ('Bariloche', 'Argentina');
INSERT INTO exampleapi.city (name, country) VALUES ('Londres', 'Inglaterra');
INSERT INTO exampleapi.city (name, country) VALUES ('Miami', 'EEUU');
INSERT INTO exampleapi.city (name, country) VALUES ('Paris', 'Francia');